name: LaTeX Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install LaTeX and Biber
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full biber

      - name: Ensure .bib file exists
        run: |
          if [ ! -f dissertation/my.bib ]; then
            echo "Error: dissertation/my.bib file not found!"
            exit 1
          fi

      - name: Compile LaTeX document with Biber
        env:
          BIBINPUTS: "./dissertation:"  # Path to find .bib files
          TEXINPUTS: "./dissertation:"  # Path to find .tex files
        run: |
          cd dissertation
          latexmk -pdf -bibtex -shell-escape -synctex=1 -interaction=nonstopmode -f main.tex
