name: LaTeX Build

on:
  push:
    branches:
      - main  # Replace with your target branch if needed
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set up LaTeX environment
        uses: dante-ev/latex-action@2023-A
        with:
          root_file: dissertation/main.tex

      - name: Ensure .bib file exists
        run: |
          if [ ! -f dissertation/my.bib ]; then
            echo "Error: dissertation/my.bib file not found!"
            exit 1
          fi

      - name: Compile LaTeX document with BibTeX
        env:
          BIBINPUTS: "./dissertation:"  # Set path to dissertation folder for .bib files
        run: |
          cd dissertation
          latexmk -pdf -bibtex -shell-escape -synctex=1 -interaction=nonstopmode -f main.tex
